# Site settings
name: System Design
email: ashi.sinha.87@gmail.com
author: Ashish Sinha
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/sinhaashish/
baseurl: "/system-design"
description: Design your Own World
meta_description: Design a highly available scalabe System
motto: Design a highly available scalabe System
banner: When you see a person without a smile, give them one of yours.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: sinhaashish

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

